on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '11 4 * * *'

name: Daily Release

jobs:
  release:
    name: Daily Release
    runs-on: ubuntu-20.04
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: Daily ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
